export const s = {
  pageHeader:    { display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 22, gap: 16 },
  pageTitle:     { fontSize: 26, fontWeight: 800, color: '#1A1A1A', margin: 0 },
  pageSubtitle:  { fontSize: 15, color: '#999', marginTop: 4, fontWeight: 500 },
  addBtn:        { display: 'flex', alignItems: 'center', gap: 8, padding: '13px 26px', background: '#CC1010', color: '#fff', border: 'none', borderRadius: 10, fontSize: 15, fontWeight: 700, cursor: 'pointer', boxShadow: '0 4px 14px rgba(204,16,16,0.25)', flexShrink: 0 },
  filterRow:     { display: 'flex', alignItems: 'center', gap: 12, marginBottom: 18, flexWrap: 'wrap' },
  filterLabel:   { display: 'flex', alignItems: 'center', gap: 6, fontSize: 15, fontWeight: 600, color: '#555', whiteSpace: 'nowrap' },
  monthInput:    { padding: '10px 16px', fontSize: 15, fontFamily: 'Cairo,sans-serif', border: '1.5px solid #E8E8E8', borderRadius: 9, background: '#fff', color: '#1A1A1A', direction: 'ltr' },
  clearFilterBtn:{ padding: '10px 18px', border: '1.5px solid #E8E8E8', borderRadius: 9, background: '#fff', color: '#767676', fontSize: 14, fontWeight: 600, cursor: 'pointer' },
  statsRow:      { display: 'flex', gap: 14, marginBottom: 18, flexWrap: 'wrap' },
  infoBanner:    { display: 'flex', alignItems: 'flex-start', gap: 10, padding: '12px 16px', background: '#EFF6FF', border: '1px solid #BFDBFE', borderRadius: 10, marginBottom: 18, fontSize: 14, color: '#1A4E8E', lineHeight: 1.6 },
  tableWrap:     { background: '#fff', borderRadius: 14, border: '1px solid #EBEBEB', overflow: 'auto' },
  centered:      { textAlign: 'center', padding: '64px 20px' },
  spinner:       { width: 38, height: 38, border: '3px solid #F0F0F0', borderTopColor: '#CC1010', borderRadius: '50%', animation: 'spin 0.8s linear infinite', margin: '0 auto' },
  table:         { width: '100%', borderCollapse: 'collapse', minWidth: 600 },
  th:            { padding: '15px 18px', textAlign: 'right', fontSize: 13, fontWeight: 700, color: '#B0B0B0', background: '#FAFAFA', borderBottom: '1px solid #EBEBEB', whiteSpace: 'nowrap' },
  tr:            { transition: 'background 0.15s' },
  td:            { padding: '14px 18px', fontSize: 15, color: '#2D2D2D', borderBottom: '1px solid #F5F5F5', verticalAlign: 'middle' },
  tdNum:         { color: '#C0C0C0', fontSize: 13, width: 40, textAlign: 'center' },
  empAvatar:     { width: 36, height: 36, borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 17, flexShrink: 0 },
  amountBadge:   { display: 'inline-flex', padding: '6px 14px', borderRadius: 99, fontSize: 14, fontWeight: 800, background: 'rgba(204,16,16,0.08)', color: '#CC1010', whiteSpace: 'nowrap' },
  editBtn:       { display: 'flex', alignItems: 'center', gap: 6, padding: '8px 14px', background: '#F0F7FF', color: '#1A6EB0', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer' },
  deleteBtn:     { display: 'flex', alignItems: 'center', gap: 6, padding: '8px 14px', background: '#FFF5F5', color: '#CC1010', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer' },
  mobileCard:    { background: '#fff', border: '1px solid #EBEBEB', borderRadius: 12, padding: '16px', display: 'flex', flexDirection: 'column', gap: 12 },
  mobileCardTop: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  mobileCardMeta:{ display: 'flex', gap: 14, flexWrap: 'wrap' },
  metaItem:      { display: 'flex', alignItems: 'center', gap: 5, fontSize: 13, color: '#767676' },
  mobileCardReason: { fontSize: 13, color: '#92400E', background: '#FFFBEB', padding: '7px 11px', borderRadius: 7, border: '1px solid #FEF3C7' },
  mobileCardActions:{ display: 'flex', gap: 8 },
  formGrid:      { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0 18px' },
  input:         { padding: '12px 16px', fontSize: 15, fontFamily: 'Cairo,sans-serif', border: '1.5px solid #E8E8E8', borderRadius: 9, background: '#FAFAFA', color: '#1A1A1A', direction: 'rtl', width: '100%' },
  modalNote:     { display: 'flex', alignItems: 'center', gap: 8, padding: '11px 16px', background: '#FFFBEB', border: '1px solid #FCD34D', borderRadius: 9, fontSize: 14, color: '#92400E', marginBottom: 20 },
  previewBox:    { background: '#FAFAFA', border: '1.5px solid #EBEBEB', borderRadius: 12, padding: '16px 20px', marginBottom: 22 },
  previewTitle:  { display: 'flex', alignItems: 'center', gap: 8, fontSize: 14, fontWeight: 700, color: '#CC1010', marginBottom: 12 },
  previewNetRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '11px 0 2px', marginTop: 8, borderTop: '2px solid #E0E0E0' },
  modalFooter:   { display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 4 },
  cancelBtn:     { padding: '12px 24px', border: '1.5px solid #E0E0E0', borderRadius: 9, background: '#fff', color: '#4A4A4A', fontSize: 15, fontWeight: 600, cursor: 'pointer' },
  submitBtn:     { padding: '12px 28px', border: 'none', borderRadius: 9, background: '#CC1010', color: '#fff', fontSize: 15, fontWeight: 700, cursor: 'pointer', boxShadow: '0 4px 14px rgba(204,16,16,0.2)' },
};
