export const s = {
  page:         { animation: 'fadeIn 0.3s ease' },
  pageHeader:   { display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 28, gap: 16 },
  pageTitle:    { fontSize: 26, fontWeight: 800, color: '#1A1A1A', margin: 0 },
  pageSubtitle: { fontSize: 15, color: '#999', marginTop: 4, fontWeight: 500 },
  addBtn:       { display: 'flex', alignItems: 'center', gap: 8, padding: '13px 26px', background: '#CC1010', color: '#fff', border: 'none', borderRadius: 10, fontSize: 15, fontWeight: 700, cursor: 'pointer', boxShadow: '0 4px 14px rgba(204,16,16,0.25)', flexShrink: 0 },
  statsRow:     { display: 'flex', gap: 16, marginBottom: 26, flexWrap: 'wrap' },
  searchWrap:   { position: 'relative', marginBottom: 22 },
  searchInput:  { width: '100%', padding: '13px 50px 13px 16px', fontSize: 15, fontFamily: 'Cairo,sans-serif', border: '1.5px solid #E8E8E8', borderRadius: 10, background: '#fff', color: '#1A1A1A', direction: 'rtl' },
  clearBtn:     { position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', color: '#B0B0B0', cursor: 'pointer', display: 'flex', padding: 2 },
  tableWrap:    { background: '#fff', borderRadius: 14, border: '1px solid #EBEBEB', overflow: 'auto' },
  loadingState: { textAlign: 'center', padding: '60px 20px', color: '#999' },
  spinner:      { width: 36, height: 36, border: '3px solid #F0F0F0', borderTopColor: '#CC1010', borderRadius: '50%', animation: 'spin 0.8s linear infinite', margin: '0 auto 14px' },
  emptyState:   { textAlign: 'center', padding: '60px 20px' },
  emptyIcon:    { fontSize: 52, marginBottom: 14 },
  emptyText:    { color: '#999', fontSize: 16, marginBottom: 20 },
  emptyBtn:     { padding: '12px 28px', background: '#CC1010', color: '#fff', border: 'none', borderRadius: 9, fontSize: 15, fontWeight: 600, cursor: 'pointer' },
  table:        { width: '100%', borderCollapse: 'collapse', minWidth: 700 },
  th:           { padding: '15px 18px', textAlign: 'right', fontSize: 13, fontWeight: 700, color: '#999', background: '#FAFAFA', borderBottom: '1px solid #EBEBEB', whiteSpace: 'nowrap' },
  tr:           { transition: 'background 0.15s' },
  td:           { padding: '15px 18px', fontSize: 15, color: '#2D2D2D', borderBottom: '1px solid #F5F5F5', verticalAlign: 'middle' },
  tdNum:        { color: '#B0B0B0', fontSize: 14, width: 44, textAlign: 'center' },
  nameCell:     { display: 'flex', alignItems: 'center', gap: 12 },
  empAvatar:    { width: 38, height: 38, borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  empName:      { fontWeight: 600 },
  badge:        { display: 'inline-flex', alignItems: 'center', padding: '4px 12px', borderRadius: 99, fontSize: 13, fontWeight: 600 },
  actionBtns:   { display: 'flex', gap: 8, alignItems: 'center' },
  editBtn:      { display: 'flex', alignItems: 'center', gap: 6, padding: '8px 14px', background: '#F0F7FF', color: '#1A6EB0', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer' },
  deleteBtn:    { display: 'flex', alignItems: 'center', gap: 6, padding: '8px 14px', background: '#FFF5F5', color: '#CC1010', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer' },
  formGrid:     { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '18px 22px', marginBottom: 26 },
  input:        { padding: '12px 16px', fontSize: 15, fontFamily: 'Cairo,sans-serif', border: '1.5px solid #E8E8E8', borderRadius: 9, background: '#FAFAFA', color: '#1A1A1A', direction: 'rtl', width: '100%' },
  modalFooter:  { display: 'flex', gap: 10, justifyContent: 'flex-end' },
  cancelBtn:    { padding: '12px 26px', border: '1.5px solid #E0E0E0', borderRadius: 9, background: '#fff', color: '#4A4A4A', fontSize: 15, fontWeight: 600, cursor: 'pointer' },
  submitBtn:    { padding: '12px 30px', border: 'none', borderRadius: 9, background: '#CC1010', color: '#fff', fontSize: 15, fontWeight: 700, cursor: 'pointer', boxShadow: '0 4px 14px rgba(204,16,16,0.2)' },
};
